title: Dawon Ahn
author: Dawon Ahn
avatar: /logo.png
email: dahn017@ucr.edu

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

remote_theme: ngzhio/jekyll-theme-hamilton

paginate: 10


# Uncomment the below line and set the tracking ID for enabling Google Analytics
google_analytics: G-1ZBGXL7M8N 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
logo: logo.png
social:
  name: Dawon Ahn
  links:
    - https://www.linkedin.com/in/dawon-ahn-110869168/
    - https://github.com/dawonahn
google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: 

# Customize

skin: daylight
location: Riverside, CA, USA
subscribe: False

